### PR TITLE
feat: add `bun.lockb` to ignorelist

### PR DESCRIPTION
**Pull request by antongolub**
BREAKING CHANGE: this adds `bun.lockb` to the strict ignorelist

### CODE REVIEW

**Comment by wraithgar** [comment]
The reason that didn't get implemented is likely due more to the fact that it was a breaking change that got lost in the npm@7 timeline than anything else.

A change like this would bubble up as a breaking change all the way up to npm itself, and would need to be coordinated with the next semver major of npm.

**Comment by wraithgar** [comment]
I added https://github.com/npm/npm-packlist/issues/48 to the v10 roadmap to see if this is something we want to finally do

**Comment by ljharb** [comment]
Are people using bun with *packages* all that much? I thought it was for apps.

**Comment by wraithgar** [comment]
changing the scope of ignored files was moved out of scope of npm 10 so that it could land eventually in node 18's main branch (which it has now!).  This will have to wait till npm 11.

**Comment by Jarred-Sumner** [comment]
I suggest adding `bun.lock` to this list as well.

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
`https://bun.sh/docs/install/lockfile` it does not look like `bun.lock` is a real thing

**Comment by ljharb** [comment]
I assume that the creator of bun meant, that it will be a real thing in the future and it'd be wise to ignore it now.

**Pull request merged**
